"""create_initial_shift_schema

Revision ID: 3ffa391cd88b
Revises: 
Create Date: 2026-09-28 00:38:50.257145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ffa391cd88b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('day_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('override_date', sa.Date(), nullable=False),
    sa.Column('mode', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('day_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_day_overrides_clerk_user_id'), ['clerk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_day_overrides_override_date'), ['override_date'], unique=False)

    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('wake_time', sa.Time(), nullable=False),
    sa.Column('bedtime_limit', sa.Time(), nullable=False),
    sa.Column('weekly_target_hours', sa.Float(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_profiles_clerk_user_id'), ['clerk_user_id'], unique=True)

    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weekly_target_hours', sa.Float(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_profile_id'), ['profile_id'], unique=False)

    op.create_table('shift_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('shift_number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('standard_start', sa.Time(), nullable=False),
    sa.Column('standard_end', sa.Time(), nullable=False),
    sa.Column('standard_break_minutes', sa.Integer(), nullable=False),
    sa.Column('rush_start', sa.Time(), nullable=False),
    sa.Column('rush_end', sa.Time(), nullable=False),
    sa.Column('rush_break_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shift_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shift_rules_profile_id'), ['profile_id'], unique=False)

    op.create_table('planned_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('start_time', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('end_time', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planned_shifts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_planned_shifts_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_planned_shifts_clerk_user_id'), ['clerk_user_id'], unique=False)

    op.create_table('session_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clerk_user_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('planned_shift_id', sa.Integer(), nullable=True),
    sa.Column('actual_start', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('actual_end', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('scheduled_start', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('scheduled_end', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('gross_minutes', sa.Integer(), nullable=False),
    sa.Column('deducted_minutes', sa.Integer(), nullable=False),
    sa.Column('net_minutes', sa.Integer(), nullable=False),
    sa.Column('variance_type', sa.Enum('ON_TIME', 'LATE_START', 'EARLY_START', 'EARLY_EXIT', name='variancetype'), nullable=False),
    sa.Column('variance_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('logged_date', sa.Date(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['planned_shift_id'], ['planned_shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_logs_activity_id'), ['activity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_logs_clerk_user_id'), ['clerk_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_logs_planned_shift_id'), ['planned_shift_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_logs_planned_shift_id'))
        batch_op.drop_index(batch_op.f('ix_session_logs_clerk_user_id'))
        batch_op.drop_index(batch_op.f('ix_session_logs_activity_id'))

    op.drop_table('session_logs')
    with op.batch_alter_table('planned_shifts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_planned_shifts_clerk_user_id'))
        batch_op.drop_index(batch_op.f('ix_planned_shifts_activity_id'))

    op.drop_table('planned_shifts')
    with op.batch_alter_table('shift_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shift_rules_profile_id'))

    op.drop_table('shift_rules')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_profile_id'))
        batch_op.drop_index(batch_op.f('ix_activities_name'))

    op.drop_table('activities')
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_profiles_clerk_user_id'))

    op.drop_table('user_profiles')
    with op.batch_alter_table('day_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_day_overrides_override_date'))
        batch_op.drop_index(batch_op.f('ix_day_overrides_clerk_user_id'))

    op.drop_table('day_overrides')
    # ### end Alembic commands ###
